name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  # Xiaomi
  build-veux-pixelos-a17:
    name: "Build veux (PixelOS A17, ReSukiSU + SUSFS)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-veux-pixelos-a17.yml
    secrets: inherit